### ISSUE TITLE
How difficult is it to adhere to correct strategy for constructing Scan instances, Hamiltonian instances, etc?

### ISSUE THREAD

**Issue by ddkohler** [wright-group/NISE#10]
In NISE's current implementation, the mantra for setting up a scan is to always set parameters before initiating.  That is, if you want to have delay 1 (d1) set to -200, call `exp.set_coord(d1, -200)` before establishing a scan.  This strategy applies to hamiltonians as well--change the class properties (tau, w_ag, etc.) before creating an instance.  If you don't, initialization will not properly work.  This workflow strategy is not enforced in any way in the code, but deviating can result in undesirable behavior.  

As an example, consider changing the dephasing time within a hamiltonian class.  The correct way to do this is:

`H.Omega.tau = 25.`
`H_instance = H.Omega()`

You might think you can just change the instance after it is created:

`H_instance = H.Omega()`
`H_instance.tau = 25.`

This, however, might not work because initialization can create new attributes that relied on the class value of tau.  Renaming the variable after initialization does not change said attributes.  This implementation is easier for the writer of the hamiltonian, because one does not need to consider how to adapt the hamiltonian to variable changes after initialization.  More generally, this is the case for construction of scan and inhomogeneity instances as well.  

I hope I've laid out the paradigm well enough.  The question is this:  is it okay for typical usage?  Obviously, the problems I've listed above can be overcome, but if the burden on the scripter to adhere to this is not too large, I might ignore these issues for now.

**Comment by untzag** [comment]
What if `scan` accepted a non-initialized Hamiltonian object?

``` python
import NISE
import NISE.experiments.trive as trive
import NISE.hamiltonians.H0 as H

if __name__ == '__main__':
    tau = 25. #set all coherence times the same
    H.Omega.tau_ag = tau
    H.Omega.tau_2aa = tau
    H.Omega.tau_2ag = tau
    out2 = trive.exp.scan(w1, w2, H=H)
```

Then inside `scan`:

``` python
H = H.Omega()
```

Wouldn't require you to change anything except one line in `scan`.

**Comment by ddkohler** [comment]
Something like that would be how I would solve the problem.  There were some reasons why I have avoided assigning the class itself to a scan object--most of it has to do with when you have multiple scan objects at the same time.  If they have different parameters, there's no good way to define the class such that they both agree.  The only way I can think of for resolving this is if we have separate class objects for each scan object.  This of course seems very similar to just giving each scans their own instances.  

What I would probably do is delay class initialization until the scan.run is called.  So initialization of a can would point the scan object to a hamiltonian class, but the instance is not set until it is absolutely needed (scan.run()).  Similarly, the scan will inherit experimental parameters for the pulses (the experiment instance) only when the run command is issued.  

As I say it, I guess I am convinced it's worth it to change it this way--I think users will find it intuitive if they can change the class all the way up until it's decided you want to run.  I'll change it.
