### ISSUE TITLE
phasing data properly for smearing operation

### ISSUE THREAD

**Issue by ddkohler** [wright-group/NISE#5]
As of right now, data from different frequency slices and different delays are not correctly phased for smearing operation.  As a result, smearing can produce spontaneous rephasing of the output coherence, especially when the output changes it's phase relationship to the last pulse (i.e. when the last pulse of a pathway is not the last pulse that arrives).

**Comment by ddkohler** [comment]
Upon further investigation, it appears simulated data must be phased to a particular pulse, not to a fixed lab time point (which, in hindsight is obvious--nothing is special about t=0 when any pulse position can move).  Current fix:  smear now has an kwarg to specify which pulse (if any) you want to phase to before smearing.  This dependence on the pulse position is still being investigated.

**Comment by untzag** [comment]
Does this mean the 'blip' in pw1 around zero delay is wrong?

**Comment by ddkohler** [comment]
Not yet at a point to say for sure what it's supposed to be like, but the blip, as it was observed, was an instance of the spontaneous rephasing.  My money is it was wrong.

**Comment by ddkohler** [comment]
Latest update has what I believe is the bug fix.  Data needs to be phased according to both colors and delays of the beams.  The kwarg mentioned above was not necessary, so smear will be called as it has been.
