### ISSUE TITLE
make axis names and labels more compatible with WrightTools

### ISSUE THREAD

**Issue by untzag** [wright-group/NISE#9]
Here are the details of how labels and names work in `WrightTools`.
1. Names are user friendly strings like `'w1'`, `'d2'`, `'wm'` that allow for quick understanding and interaction with data. For example you might say `data.level('d2', -3)`. Of course, for internal programmatic use the string is arbitrary. For now, I pass your 'name' object but that makes it harder to interact as I intend with the data object.
2. `WrightTools` axis objects are meant to assemble their own labels. They do this by referring to a list called `label_seed` which contains, essentially, the content for the subscripts of each symbol. They also contain their own units so they can refer to a dictionary to assemble the label. For example, a `label_seed` `['1', 'm']` and units `'wn'` would become label `$\mathsf{\bar\nu_{1}=\bar\nu_{m}\,\left(cm^{-1}\right)}$`. Right now I'm using your `also` object which works enough to tell what's going on but isn't in the intuitive representation of the experimental space.

![test](https://cloud.githubusercontent.com/assets/8051086/7443359/df705948-f109-11e4-83ad-4a4e0cc1348a.png)

Neither of these issues are important, really. Change these properties if you fee inclined and it is useful to you. In the long run, it would be very cool if you sub-classed the `WrightTools` `Axis` object to make `NISE.lib.axis.Axis`. Not sure how difficult this would be.

Also - is there any way for me to access the 'constants' of a measure or scan object?

**Comment by ddkohler** [comment]
We already discussed this offline, but I thought it might be useful to put this info in here for the record.  
1.  Names can be compiled by conversing with the pulse class that corresponds to the scan.  (Scan objects do not internalize the pulse class, but instead store the name of the class.  The class can then be called by looking up the class name in the pulse module dictionary.)  Each pulse class has a dictionary (named "cols") that relates the indices of the pulse parameters to a letter for easy interpretation.  If the goal is to come up with easy names, you can construct them by noting which coordinates of the lasers are being scanned with a certain axis (Axis.pulse_ind provides the parameter index, and Axis.pulse_var provides which beam it is.  Axis.also might include another co-scanned beam).  Connecting a parameter index to a name is as easy as looking up the index in the cols dictionary.  
2.  By the lookup strategy above, a label_seed can be generated for NISE axes as well.  The 'cols' dictionary will supply the label such as 'w' or 'd', and the pulse index can be translated into appropriate subscripts.  wrt subclassing WrightTools Axis object, it is a promising goal, and i hope to do that at some point, but for now if there is a from_NISE function being made, I feel it's not that urgent to work on.  If I had to choose between the two, i think from_NISE will be an easier thing to tackle.  

If the parameters were not scanned, their default values can be found under the scan object attribute 'positions', which is an n x m array (n is the number of pulses, m is the number of parameters) which shows the default parameters for the beams.

**Comment by untzag** [comment]
OK well I've incorporated these ideas into from_NISE. This is now the default plot made from a 2D frequency NISE measure object:

![figure_1](https://cloud.githubusercontent.com/assets/8051086/7526979/a3fecb66-f4dc-11e4-9056-39c0d1ef8515.png)

I still don't like it because it notates in the context of the simulation rather than the experiment. In a perfect world I would want the experiment objects to contain some reference that translates the NISE axes into the experimental notation (2, 2' etc). However, it is fully usable as is.

Here is the snippet of code you would need to plot the above using `WrightTools`:

``` python

import WrightTools as wt

#get your scan object by loading from file or whatever

slitwidth = 120.
measure = m.Measure(scan, m.Mono, m.SLD)
m.Mono.slitwidth=slitwidth
measure.run(save = False)

data = wt.data.from_NISE(measure)
artist = wt.artists.mpl_2D(data, 0, 1)
artist.plot()

```
